import './fetch.js';
import './create-new-book.js';
import './map.js';
import './message-succes.js';
import './message-error.js';
import './map.js';
import './user-form.js';
import './popup.js';
import './avatar.js';
